### ISSUE TITLE
Voices available in web are not available in app.

### ISSUE THREAD

**Issue by ajayjg** [changemyminds/GCP_TTS_ByAPIKEY#5]
Hi,

The voice style "**fr-FR-Wavenet-E**" in **Français (France)**, is  available in webpage but not getting in app when trying styles. Any clue why is that missing. 

<img width="961" alt="Screen Shot 2021-02-19 at 6 17 36 PM" src="https://user-images.githubusercontent.com/26141914/108506604-14f7f500-72df-11eb-99e0-8f6559040b0f.png">

<img width="481" alt="Screen Shot 2021-02-19 at 6 17 56 PM" src="https://user-images.githubusercontent.com/26141914/108506620-17f2e580-72df-11eb-88c8-2f63866a3ced.png">

**Comment by changemyminds** [comment]
Thanks for your answer. I fixed the bug. The problem is [here](https://github.com/changemyminds/Google-Cloud-TTS-Android/commit/b514ae4c914b9fa112e15fce522eb45daebac181#r47342124).

**Comment by ajayjg** [comment]
@changemyminds This was really quick. Thanks for the fix.
